services:
  mongo:
    image: mongo:7
    container_name: kenko-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: kenko

volumes:
  mongo-data:
