import "dotenv/config"
import { MongoClient, ObjectId } from "mongodb"

type Equipment = "barbell" | "dumbbell" | "cable" | "machine" | "resistance_band" | "bodyweight" | "other"

type MuscleRegion = "torso" | "arms" | "lower_body"

type Muscle =
  | "chest"
  | "abs"
  | "back"
  | "lower_back"
  | "trapezius"
  | "neck"
  | "shoulders"
  | "biceps"
  | "triceps"
  | "forearms"
  | "glutes"
  | "quads"
  | "hamstrings"
  | "calves"
  | "abductors"
  | "adductors"

interface GlobalExercise {
  _id: ObjectId
  userId: null
  isGlobal: true
  name: string
  muscleGroup: {
    region: MuscleRegion
    muscle: Muscle
  }
  equipment: Equipment
  createdAt: Date
  updatedAt: Date
}

const now = new Date()

const exercises: GlobalExercise[] = [
  // ─── CHEST ───────────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Barbell Bench Press",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Incline Barbell Bench Press",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Decline Barbell Bench Press",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Dumbbell Bench Press",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Incline Dumbbell Bench Press",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Dumbbell Fly",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Incline Dumbbell Fly",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Cable Fly",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Low Cable Fly",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Machine Chest Press",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Pec Deck",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Push-Up",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Wide Push-Up",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Chest Dip",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },

  // ─── ABS ─────────────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Crunch",
    muscleGroup: { region: "torso", muscle: "abs" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Bicycle Crunch",
    muscleGroup: { region: "torso", muscle: "abs" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Leg Raise",
    muscleGroup: { region: "torso", muscle: "abs" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Hanging Leg Raise",
    muscleGroup: { region: "torso", muscle: "abs" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Plank",
    muscleGroup: { region: "torso", muscle: "abs" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Side Plank",
    muscleGroup: { region: "torso", muscle: "abs" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Ab Wheel Rollout",
    muscleGroup: { region: "torso", muscle: "abs" },
    equipment: "other",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Cable Crunch",
    muscleGroup: { region: "torso", muscle: "abs" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Decline Sit-Up",
    muscleGroup: { region: "torso", muscle: "abs" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Russian Twist",
    muscleGroup: { region: "torso", muscle: "abs" },
    equipment: "other",
    createdAt: now,
    updatedAt: now,
  },

  // ─── BACK ─────────────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Barbell Row",
    muscleGroup: { region: "torso", muscle: "back" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Pendlay Row",
    muscleGroup: { region: "torso", muscle: "back" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Dumbbell Row",
    muscleGroup: { region: "torso", muscle: "back" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Cable Row",
    muscleGroup: { region: "torso", muscle: "back" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Lat Pulldown",
    muscleGroup: { region: "torso", muscle: "back" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Wide Grip Lat Pulldown",
    muscleGroup: { region: "torso", muscle: "back" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Pull-Up",
    muscleGroup: { region: "torso", muscle: "back" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Chin-Up",
    muscleGroup: { region: "torso", muscle: "back" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Machine Row",
    muscleGroup: { region: "torso", muscle: "back" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Resistance Band Row",
    muscleGroup: { region: "torso", muscle: "back" },
    equipment: "resistance_band",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "T-Bar Row",
    muscleGroup: { region: "torso", muscle: "back" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },

  // ─── LOWER BACK ───────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Deadlift",
    muscleGroup: { region: "torso", muscle: "lower_back" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Romanian Deadlift",
    muscleGroup: { region: "torso", muscle: "lower_back" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Sumo Deadlift",
    muscleGroup: { region: "torso", muscle: "lower_back" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Dumbbell Romanian Deadlift",
    muscleGroup: { region: "torso", muscle: "lower_back" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Back Extension",
    muscleGroup: { region: "torso", muscle: "lower_back" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Good Morning",
    muscleGroup: { region: "torso", muscle: "lower_back" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Hyperextension",
    muscleGroup: { region: "torso", muscle: "lower_back" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },

  // ─── TRAPEZIUS ────────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Barbell Shrug",
    muscleGroup: { region: "torso", muscle: "trapezius" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Dumbbell Shrug",
    muscleGroup: { region: "torso", muscle: "trapezius" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Cable Shrug",
    muscleGroup: { region: "torso", muscle: "trapezius" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Face Pull",
    muscleGroup: { region: "torso", muscle: "trapezius" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Rack Pull",
    muscleGroup: { region: "torso", muscle: "trapezius" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },

  // ─── NECK ─────────────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Neck Flexion",
    muscleGroup: { region: "torso", muscle: "neck" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Neck Extension",
    muscleGroup: { region: "torso", muscle: "neck" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Plate Neck Curl",
    muscleGroup: { region: "torso", muscle: "neck" },
    equipment: "other",
    createdAt: now,
    updatedAt: now,
  },

  // ─── SHOULDERS ────────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Barbell Overhead Press",
    muscleGroup: { region: "arms", muscle: "shoulders" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Seated Dumbbell Press",
    muscleGroup: { region: "arms", muscle: "shoulders" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Arnold Press",
    muscleGroup: { region: "arms", muscle: "shoulders" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Dumbbell Lateral Raise",
    muscleGroup: { region: "arms", muscle: "shoulders" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Cable Lateral Raise",
    muscleGroup: { region: "arms", muscle: "shoulders" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Dumbbell Front Raise",
    muscleGroup: { region: "arms", muscle: "shoulders" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Barbell Front Raise",
    muscleGroup: { region: "arms", muscle: "shoulders" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Reverse Fly",
    muscleGroup: { region: "arms", muscle: "shoulders" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Machine Shoulder Press",
    muscleGroup: { region: "arms", muscle: "shoulders" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Resistance Band Lateral Raise",
    muscleGroup: { region: "arms", muscle: "shoulders" },
    equipment: "resistance_band",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Pike Push-Up",
    muscleGroup: { region: "arms", muscle: "shoulders" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },

  // ─── BICEPS ───────────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Barbell Curl",
    muscleGroup: { region: "arms", muscle: "biceps" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "EZ Bar Curl",
    muscleGroup: { region: "arms", muscle: "biceps" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Dumbbell Curl",
    muscleGroup: { region: "arms", muscle: "biceps" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Hammer Curl",
    muscleGroup: { region: "arms", muscle: "biceps" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Incline Dumbbell Curl",
    muscleGroup: { region: "arms", muscle: "biceps" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Concentration Curl",
    muscleGroup: { region: "arms", muscle: "biceps" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Cable Curl",
    muscleGroup: { region: "arms", muscle: "biceps" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Preacher Curl",
    muscleGroup: { region: "arms", muscle: "biceps" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Resistance Band Curl",
    muscleGroup: { region: "arms", muscle: "biceps" },
    equipment: "resistance_band",
    createdAt: now,
    updatedAt: now,
  },

  // ─── TRICEPS ──────────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Close Grip Bench Press",
    muscleGroup: { region: "arms", muscle: "triceps" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Skull Crusher",
    muscleGroup: { region: "arms", muscle: "triceps" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Tricep Pushdown",
    muscleGroup: { region: "arms", muscle: "triceps" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Rope Pushdown",
    muscleGroup: { region: "arms", muscle: "triceps" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Overhead Tricep Extension",
    muscleGroup: { region: "arms", muscle: "triceps" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Cable Overhead Tricep Extension",
    muscleGroup: { region: "arms", muscle: "triceps" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Tricep Dip",
    muscleGroup: { region: "arms", muscle: "triceps" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Diamond Push-Up",
    muscleGroup: { region: "arms", muscle: "triceps" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Kickback",
    muscleGroup: { region: "arms", muscle: "triceps" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Machine Tricep Press",
    muscleGroup: { region: "arms", muscle: "triceps" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },

  // ─── FOREARMS ─────────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Barbell Wrist Curl",
    muscleGroup: { region: "arms", muscle: "forearms" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Reverse Wrist Curl",
    muscleGroup: { region: "arms", muscle: "forearms" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Dumbbell Wrist Curl",
    muscleGroup: { region: "arms", muscle: "forearms" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Farmer's Carry",
    muscleGroup: { region: "arms", muscle: "forearms" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Plate Pinch",
    muscleGroup: { region: "arms", muscle: "forearms" },
    equipment: "other",
    createdAt: now,
    updatedAt: now,
  },

  // ─── GLUTES ───────────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Barbell Hip Thrust",
    muscleGroup: { region: "lower_body", muscle: "glutes" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Dumbbell Hip Thrust",
    muscleGroup: { region: "lower_body", muscle: "glutes" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Glute Bridge",
    muscleGroup: { region: "lower_body", muscle: "glutes" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Cable Kickback",
    muscleGroup: { region: "lower_body", muscle: "glutes" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Donkey Kick",
    muscleGroup: { region: "lower_body", muscle: "glutes" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Romanian Deadlift",
    muscleGroup: { region: "lower_body", muscle: "glutes" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Sumo Squat",
    muscleGroup: { region: "lower_body", muscle: "glutes" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },

  // ─── QUADS ────────────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Barbell Back Squat",
    muscleGroup: { region: "lower_body", muscle: "quads" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Barbell Front Squat",
    muscleGroup: { region: "lower_body", muscle: "quads" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Goblet Squat",
    muscleGroup: { region: "lower_body", muscle: "quads" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Leg Press",
    muscleGroup: { region: "lower_body", muscle: "quads" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Leg Extension",
    muscleGroup: { region: "lower_body", muscle: "quads" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Bulgarian Split Squat",
    muscleGroup: { region: "lower_body", muscle: "quads" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Walking Lunge",
    muscleGroup: { region: "lower_body", muscle: "quads" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Barbell Lunge",
    muscleGroup: { region: "lower_body", muscle: "quads" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Bodyweight Squat",
    muscleGroup: { region: "lower_body", muscle: "quads" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Hack Squat",
    muscleGroup: { region: "lower_body", muscle: "quads" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Step Up",
    muscleGroup: { region: "lower_body", muscle: "quads" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },

  // ─── HAMSTRINGS ───────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Lying Leg Curl",
    muscleGroup: { region: "lower_body", muscle: "hamstrings" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Seated Leg Curl",
    muscleGroup: { region: "lower_body", muscle: "hamstrings" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Nordic Hamstring Curl",
    muscleGroup: { region: "lower_body", muscle: "hamstrings" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Dumbbell Romanian Deadlift",
    muscleGroup: { region: "lower_body", muscle: "hamstrings" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Cable Hamstring Curl",
    muscleGroup: { region: "lower_body", muscle: "hamstrings" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Glute Ham Raise",
    muscleGroup: { region: "lower_body", muscle: "hamstrings" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },

  // ─── CALVES ───────────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Standing Calf Raise",
    muscleGroup: { region: "lower_body", muscle: "calves" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Seated Calf Raise",
    muscleGroup: { region: "lower_body", muscle: "calves" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Bodyweight Calf Raise",
    muscleGroup: { region: "lower_body", muscle: "calves" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Donkey Calf Raise",
    muscleGroup: { region: "lower_body", muscle: "calves" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Leg Press Calf Raise",
    muscleGroup: { region: "lower_body", muscle: "calves" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },

  // ─── ABDUCTORS ────────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Hip Abduction Machine",
    muscleGroup: { region: "lower_body", muscle: "abductors" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Cable Hip Abduction",
    muscleGroup: { region: "lower_body", muscle: "abductors" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Resistance Band Abduction",
    muscleGroup: { region: "lower_body", muscle: "abductors" },
    equipment: "resistance_band",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Lateral Band Walk",
    muscleGroup: { region: "lower_body", muscle: "abductors" },
    equipment: "resistance_band",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Clamshell",
    muscleGroup: { region: "lower_body", muscle: "abductors" },
    equipment: "resistance_band",
    createdAt: now,
    updatedAt: now,
  },

  // ─── ADDUCTORS ────────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Hip Adduction Machine",
    muscleGroup: { region: "lower_body", muscle: "adductors" },
    equipment: "machine",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Cable Hip Adduction",
    muscleGroup: { region: "lower_body", muscle: "adductors" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Sumo Deadlift",
    muscleGroup: { region: "lower_body", muscle: "adductors" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Copenhagen Plank",
    muscleGroup: { region: "lower_body", muscle: "adductors" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Resistance Band Adduction",
    muscleGroup: { region: "lower_body", muscle: "adductors" },
    equipment: "resistance_band",
    createdAt: now,
    updatedAt: now,
  },

  // ─── ADDITIONAL CHEST ─────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Cable Chest Press",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Decline Dumbbell Fly",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Resistance Band Push-Up",
    muscleGroup: { region: "torso", muscle: "chest" },
    equipment: "resistance_band",
    createdAt: now,
    updatedAt: now,
  },

  // ─── ADDITIONAL BACK ──────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Straight Arm Pulldown",
    muscleGroup: { region: "torso", muscle: "back" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Inverted Row",
    muscleGroup: { region: "torso", muscle: "back" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Meadows Row",
    muscleGroup: { region: "torso", muscle: "back" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },

  // ─── ADDITIONAL ABS ───────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Dragon Flag",
    muscleGroup: { region: "torso", muscle: "abs" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Hollow Body Hold",
    muscleGroup: { region: "torso", muscle: "abs" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Weighted Crunch",
    muscleGroup: { region: "torso", muscle: "abs" },
    equipment: "other",
    createdAt: now,
    updatedAt: now,
  },

  // ─── ADDITIONAL SHOULDERS ─────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Upright Row",
    muscleGroup: { region: "arms", muscle: "shoulders" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Cable Front Raise",
    muscleGroup: { region: "arms", muscle: "shoulders" },
    equipment: "cable",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Handstand Push-Up",
    muscleGroup: { region: "arms", muscle: "shoulders" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },

  // ─── ADDITIONAL BICEPS ────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Spider Curl",
    muscleGroup: { region: "arms", muscle: "biceps" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Cross Body Hammer Curl",
    muscleGroup: { region: "arms", muscle: "biceps" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },

  // ─── ADDITIONAL TRICEPS ───────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Tate Press",
    muscleGroup: { region: "arms", muscle: "triceps" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Resistance Band Pushdown",
    muscleGroup: { region: "arms", muscle: "triceps" },
    equipment: "resistance_band",
    createdAt: now,
    updatedAt: now,
  },

  // ─── ADDITIONAL QUADS ─────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Sissy Squat",
    muscleGroup: { region: "lower_body", muscle: "quads" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Wall Sit",
    muscleGroup: { region: "lower_body", muscle: "quads" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },

  // ─── ADDITIONAL HAMSTRINGS ────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Single Leg Romanian Deadlift",
    muscleGroup: { region: "lower_body", muscle: "hamstrings" },
    equipment: "dumbbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Resistance Band Leg Curl",
    muscleGroup: { region: "lower_body", muscle: "hamstrings" },
    equipment: "resistance_band",
    createdAt: now,
    updatedAt: now,
  },

  // ─── ADDITIONAL GLUTES ────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Single Leg Glute Bridge",
    muscleGroup: { region: "lower_body", muscle: "glutes" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Kettlebell Swing",
    muscleGroup: { region: "lower_body", muscle: "glutes" },
    equipment: "other",
    createdAt: now,
    updatedAt: now,
  },

  // ─── ADDITIONAL ───────────────────────────────────────────────────
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Dead Hang",
    muscleGroup: { region: "arms", muscle: "forearms" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Trap Bar Deadlift",
    muscleGroup: { region: "torso", muscle: "lower_back" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Snatch Grip Deadlift",
    muscleGroup: { region: "torso", muscle: "trapezius" },
    equipment: "barbell",
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: new ObjectId(),
    userId: null,
    isGlobal: true,
    name: "Single Leg Calf Raise",
    muscleGroup: { region: "lower_body", muscle: "calves" },
    equipment: "bodyweight",
    createdAt: now,
    updatedAt: now,
  },
]

async function seed() {
  const uri = process.env.MONGODB_URI
  if (!uri) {
    console.error("MONGODB_URI is not set. Create a .env file with MONGODB_URI.")
    process.exit(1)
  }

  const client = new MongoClient(uri)
  try {
    await client.connect()
    const db = client.db("kenko")
    const collection = db.collection("exercises")

    const existingCount = await collection.countDocuments({ isGlobal: true })
    if (existingCount > 0) {
      console.log(`Found ${existingCount} global exercises already seeded. Skipping.`)
      return
    }

    // Backfill existing user exercises that lack isGlobal
    await collection.updateMany(
      { isGlobal: { $exists: false } },
      { $set: { isGlobal: false } },
    )

    const result = await collection.insertMany(exercises)
    console.log(`Seeded ${result.insertedCount} global exercises.`)
  } finally {
    await client.close()
  }
}

seed().catch((err) => {
  console.error("Seed failed:", err)
  process.exit(1)
})
